"""
Hadith database loader - loads verified authentic Sahih hadiths from API.
All hadiths are fetched from authentic CDN sources with Sahih grade verification.

NO HARDCODED HADITHS - all data comes from verified_hadiths.json
which is generated by fetch_authentic_hadiths.py using real hadith APIs.
"""

import json
import re
from typing import List, Dict, Tuple, Optional
from pathlib import Path

DATABASE_FILE = Path(__file__).parent / "verified_hadiths.json"

def extract_hadith_variant_info(hadith_number) -> Tuple[str, Optional[str]]:
    """
    Extract base number and variant from hadith number
    
    Args:
        hadith_number: Could be int (1234) or str ('251a', '251b', '251c', '251d')
    
    Returns:
        Tuple of (base_number_str, variant_letter or None)
        Examples: 
            1234 -> ('1234', None)
            '251a' -> ('251', 'a')
            '251b' -> ('251', 'b')
    """
    hadith_str = str(hadith_number)
    match = re.match(r'^(\d+)([a-d])$', hadith_str)
    
    if match:
        base_number = match.group(1)
        variant = match.group(2)
        return (base_number, variant)
    else:
        return (hadith_str, None)

def generate_unique_id(collection: str, hadith_number) -> str:
    """
    Generate unique identifier for a hadith
    
    Format: {collection}:{hadith_number}
    Examples: 'bukhari:1', 'muslim:251a', 'muslim:251b'
    """
    collection_clean = collection.lower().strip()
    return f"{collection_clean}:{hadith_number}"

def generate_base_id(collection: str, hadith_number) -> str:
    """
    Generate base identifier (without variant) for tracking
    
    Format: {collection}:{base_number}
    Examples: 
        'muslim:251a' -> 'muslim:251'
        'bukhari:1' -> 'bukhari:1'
    
    This is used to mark the entire hadith as posted, preventing any variant from repeating
    """
    base_number, _ = extract_hadith_variant_info(hadith_number)
    collection_clean = collection.lower().strip()
    return f"{collection_clean}:{base_number}"

def load_verified_hadiths() -> List[Dict]:
    if not DATABASE_FILE.exists():
        print(f"⚠️  WARNING: {DATABASE_FILE} not found!")
        print("   Run: python3 fetch_authentic_hadiths.py --refresh")
        return []
    
    try:
        with open(DATABASE_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
            hadiths = data.get('hadiths', [])
            print(f"✅ Loaded {len(hadiths)} verified Sahih hadiths")
            return hadiths
    except Exception as e:
        print(f"❌ Error loading hadith database: {e}")
        return []

def get_sahih_hadiths() -> List[Dict]:
    hadiths = load_verified_hadiths()
    transformed = []
    for h in hadiths:
        collection = h.get('collection', '')
        hadith_number = h.get('hadith_number', 0)
        
        # Generate unique IDs
        unique_id = generate_unique_id(collection, hadith_number)
        base_id = generate_base_id(collection, hadith_number)
        
        # Extract variant info
        base_number, variant = extract_hadith_variant_info(hadith_number)
        
        transformed.append({
            'text': h['text'],
            'primary_source': h['reference'],
            'verification_source': f"{h['source']} verified",
            'grade': 'Sahih',
            'book': h['reference'].split(' ')[0] + ' ' + h['reference'].split(' ')[1],
            'category': h.get('category', 'General'),
            'reference': h['reference'],
            'chapter': h.get('chapter', ''),
            'narrator': h.get('narrator', ''),
            'source': h.get('source', ''),
            'collection': collection,
            'hadith_number': hadith_number,
            # NEW: Unique identifier fields for tracking
            'unique_id': unique_id,        # e.g., 'muslim:251a' or 'bukhari:1'
            'base_id': base_id,            # e.g., 'muslim:251' or 'bukhari:1'
            'base_number': base_number,    # e.g., '251' or '1'
            'variant': variant             # e.g., 'a', 'b', 'c', 'd', or None
        })
    return transformed

def validate_hadith_authenticity(hadith: Dict) -> bool:
    return True

def is_substantial_hadith(hadith: Dict, min_length: int = 100) -> bool:
    """
    Check if hadith has substantial text content
    
    Some variant hadiths (like Muslim:251a/b/c/d) may have only reference text
    Example: "Muhammad b. Abu Rafi' narrated the hadith on the authority of Abu Dharr with a slight difference"
    
    This function ensures we pick variants with actual hadith content
    
    Args:
        hadith: Hadith dictionary with 'text' field
        min_length: Minimum text length to consider substantial
    
    Returns:
        True if hadith has substantial content, False otherwise
    """
    text = hadith.get('text', '').strip()
    return len(text) >= min_length

def get_hadith_stats() -> Dict:
    hadiths = load_verified_hadiths()
    if not hadiths:
        return {
            'total': 0,
            'collections': [],
            'categories': [],
            'status': 'No database found'
        }
    
    collections = {}
    categories = {}
    for h in hadiths:
        collection = h.get('collection', 'unknown')
        category = h.get('category', 'general')
        collections[collection] = collections.get(collection, 0) + 1
        categories[category] = categories.get(category, 0) + 1
    
    return {
        'total': len(hadiths),
        'collections': dict(sorted(collections.items())),
        'categories': dict(sorted(categories.items())),
        'source': 'cdn.jsdelivr.net verified',
        'grade': 'All Sahih',
        'status': 'Active'
    }

HADITHS = get_sahih_hadiths()

if __name__ == "__main__":
    stats = get_hadith_stats()
    print("=" * 70)
    print("HADITH DATABASE LOADER TEST")
    print("=" * 70)
    print(f"\nTotal Hadiths: {stats['total']}")
    print(f"Status: {stats['status']}")
    if stats['total'] > 0:
        print(f"\nCollections:")
        for collection, count in stats['collections'].items():
            print(f"  • {collection.title()}: {count} hadiths")
        hadiths = get_sahih_hadiths()
        print(f"\nSample: {hadiths[0]['reference']} - {hadiths[0]['text'][:100]}...")
